config/routes.rb
Rails.application.routes.draw do

  root 'front_pages#main'

  #CUSTOM URL
  get '/pricing' => 'front_pages#pricing'
  get '/support' => 'front_pages#support'
  get '/signin' => 'front_pages#signin'
  get '/signup' => 'front_pages#signup'

  #Resources
  resources :accounts, :users, :front_pages
  resources :dashboards do
    get '/login' => 'dashboards#login'
    get '/settings' => 'dashboards#settings'
    get '/visitors' => 'dashboards#visitors'
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/dashboard.rb
class Dashboard < ActiveRecord::Base
  belongs_to :user
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :set_dashboard, only: [:show, :edit, :update, :destroy]

  # GET /dashboards
  # GET /dashboards.json
  def index
    @dashboards = Dashboard.all
  end

  # GET /dashboards/1
  # GET /dashboards/1.json
  def show
  end

  # GET /dashboards/new
  def new
    @dashboard = Dashboard.new
  end

  # GET /dashboards/1/edit
  def edit
  end

  # POST /dashboards
  # POST /dashboards.json
  def create
    @dashboard = Dashboard.new(dashboard_params)

    respond_to do |format|
      if @dashboard.save
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully created.' }
        format.json { render :show, status: :created, location: @dashboard }
      else
        format.html { render :new }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dashboards/1
  # PATCH/PUT /dashboards/1.json
  def update
    respond_to do |format|
      if @dashboard.update(dashboard_params)
        format.html { redirect_to @dashboard, notice: 'Dashboard was successfully updated.' }
        format.json { render :show, status: :ok, location: @dashboard }
      else
        format.html { render :edit }
        format.json { render json: @dashboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dashboards/1
  # DELETE /dashboards/1.json
  def destroy
    @dashboard.destroy
    respond_to do |format|
      format.html { redirect_to dashboards_url, notice: 'Dashboard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dashboard
      @dashboard = Dashboard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dashboard_params
      params.require(:dashboard).permit(:user_id, :user_id, :website, :total_count)
    end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/_form.html.erb
<%= form_for(@dashboard) do |f| %>
  <% if @dashboard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dashboard.errors.count, "error") %> prohibited this dashboard from being saved:</h2>

      <ul>
      <% @dashboard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="field">
    <%= f.label :total_count %><br>
    <%= f.number_field :total_count %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dashboards/_login_content.html.erb
<div class="container-fluid">	
	<div class="row">
		<div class="col-sm-6">
			<div class="chart-wrapper center">
				<h1>Login<h1> 
				<input type="text" name="name" value=""> <br>
				<input type="text" name="name" value=""> <br>
				<button type="button" name="button" class="btn btn-xs btn-default">Login</button>

				<div class="chart-stage">
						<img data-src="holder.js/100%x120/white">
				</div>
				<div class="chart-notes">
					Notes about this Setting Page
				</div>
			</div>
		</div>
	</div>
</div>

app/views/dashboards/_root_content.html.erb
<div class="fix-container container-fluid">

	<div class="row">
		<div class="col-sm-6 col-md-3">
			<div class="chart-wrapper">
				<div class="chart-title">
					Total Visitor Today (20)

					<!-- dropdown panel -->
					<div class="float_right">
						<div class="dropdown">
							<button class="btn btn-xs btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
					</div>


				</div>
				<div class="chart-stage">
					<div id="grid-1-1">
						<!-- <img data-src="holder.js/100%x180/white/text:#grid-1-1"> -->
						<canvas id="canvas1" height="450" width="600"></canvas>
					</div>
				</div>
				<div class="chart-notes">
					Notes about this chart
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-3">
			<div class="chart-wrapper">
				<div class="chart-title">
					Last Country (Singapore)

					<!-- dropdown panel -->
					<div class="float_right">
						<div class="dropdown">
							<button class="btn btn-xs btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
					</div>


				</div>
				<div class="chart-stage">
					<!-- <img data-src="holder.js/100%x180/white"> -->
					<canvas id="canvas2" height="450" width="600"></canvas>
				</div>
				<div class="chart-notes">
					Notes about this chart
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-3">
			<div class="chart-wrapper">
				<div class="chart-title">
					Total Devices (3)

					<!-- dropdown panel -->
					<div class="float_right">
						<div class="dropdown">
							<button class="btn btn-xs btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
					</div>


				</div>
				<div class="chart-stage">
					<!-- <img data-src="holder.js/100%x180/white"> -->
					<canvas id="canvas3" height="450" width="600"></canvas>

				</div>
				<div class="chart-notes">
					Notes about this chart
				</div>
			</div>
		</div>
		<div class="col-sm-6 col-md-3">
			<div class="chart-wrapper">
				<div class="chart-title">
				 Last Visit (12:20pm 20 min ago)

				 <!-- dropdown panel -->
				 <div class="float_right">
					 <div class="dropdown">
						 <button class="btn btn-xs btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
							 <span class="caret"></span>
						 </button>
						 <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
							 <li><a href="#">Action</a></li>
							 <li><a href="#">Another action</a></li>
							 <li><a href="#">Something else here</a></li>
							 <li><a href="#">Separated link</a></li>
						 </ul>
					 </div>
				 </div>


				</div>
				<div class="chart-stage">
					<!-- <img data-src="holder.js/100%x180/white"> -->
					<canvas id="canvas4" height="450" width="600"></canvas>

				</div>
				<div class="chart-notes">
					Notes about this chart
				</div>
			</div>
		</div>
	</div>


	<div class="row">
		<div class="col-sm-6">
			<div class="chart-wrapper">
				<div class="chart-title">
					Total Weekly Visitors Chart

					<!-- dropdown panel -->
					<div class="float_right">
						<div class="dropdown">
							<button class="btn btn-xs btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
					</div>

				</div>
				<div class="chart-stage">
						<!-- <img data-src="holder.js/100%x120/white"> -->
						<canvas id="canvas5" height="450" width="600"></canvas>

				</div>
				<div class="chart-notes">
					Notes about this chart
				</div>
			</div>
		</div>
		<div class="col-sm-6">
			<div class="chart-wrapper">
				<div class="chart-title">
					Top Five Webpages
					<!-- dropdown panel -->
					<div class="float_right">
						<div class="dropdown">
							<button class="btn btn-xs btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
								<span class="caret"></span>
							</button>
							<ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
								<li><a href="#">Action</a></li>
								<li><a href="#">Another action</a></li>
								<li><a href="#">Something else here</a></li>
								<li><a href="#">Separated link</a></li>
							</ul>
						</div>
					</div>


				</div>
				<div class="chart-stage">
						<!-- <img data-src="holder.js/100%x120/white"> -->
						<canvas id="canvas6" height="450" width="600"></canvas>
				</div>
				<div class="chart-notes">
					Notes about this chart
				</div>
			</div>
		</div>
	</div>

</div>

app/views/dashboards/_settings_content.html.erb
<div class="container-fluid">
	
	<div class="row">
		<div class="col-sm-4">
			<div class="chart-wrapper">
			
				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>
				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-stage">
						<img data-src="holder.js/100%x120/white">
				</div>
				<div class="chart-notes">
					Notes about this Setting Page
				</div>
			</div>
		</div>
		
	</div>

app/views/dashboards/_visitors_content.html.erb
<div class="container-fluid">
	
	<div class="row">
		<div class="col-sm-12">
			<div class="chart-wrapper">
			
				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>
				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-title">
					Some Settings
					
					<button class="float_right btn btn-default btn-xs" type="button" name="button">Button</button>
				</div>

				<div class="chart-stage">
						<img data-src="holder.js/100%x120/white">
				</div>
				<div class="chart-notes">
					Notes about this Setting Page
				</div>
			</div>
		</div>
	</div>

</div>

app/views/dashboards/edit.html.erb
<h1>Editing Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dashboard %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dashboards</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>User</th>
      <th>Website</th>
      <th>Total count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dashboards.each do |dashboard| %>
      <tr>
        <td><%= dashboard.user_id %></td>
        <td><%= dashboard.user %></td>
        <td><%= dashboard.website %></td>
        <td><%= dashboard.total_count %></td>
        <td><%= link_to 'Show', dashboard %></td>
        <td><%= link_to 'Edit', edit_dashboard_path(dashboard) %></td>
        <td><%= link_to 'Destroy', dashboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dashboard', new_dashboard_path %>

app/views/dashboards/main.html.erb
<%= title "ytbryan.com (10)" %>

<body class="application">

    <%= render "layouts/navigation" %>
    <%= render "root_content" %>
    <hr>
    <p class="small text-muted">Built with &#9829; by <a href="https://keen.io">Bird Eye View</a></p>

</div>

app/views/dashboards/new.html.erb
<h1>New Dashboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dashboards_path %>

app/views/dashboards/settings.html.erb
<body class="application">

  <%= render "layouts/navigation" %>

  <%= render "settings_content" %>
    <hr>

    <p class="small text-muted">Built with &#9829; by <a href="https://keen.io">Bird Eye View</a></p>

  </div>

app/views/dashboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @dashboard.user_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @dashboard.user %>
</p>

<p>
  <strong>Website:</strong>
  <%= @dashboard.website %>
</p>

<p>
  <strong>Total count:</strong>
  <%= @dashboard.total_count %>
</p>

<%= link_to 'Edit', edit_dashboard_path(@dashboard) %> |
<%= link_to 'Back', dashboards_path %>

app/views/dashboards/visitors.html.erb
<body class="application">
  <%= render "layouts/navigation" %>
  <%= render "visitors_content" %>
  <hr>
  <p class="small text-muted">Built with &#9829; by <a href="https://keen.io">Bird Eye View</a></p>
</div>