config/routes.rb
Rails.application.routes.draw do

  root 'front_pages#main'

  #CUSTOM URL
  get '/pricing' => 'front_pages#pricing'
  get '/support' => 'front_pages#support'
  get '/signin' => 'front_pages#signin'
  get '/signup' => 'front_pages#signup'

  #Resources
  resources :accounts, :users, :front_pages
  resources :dashboards do
    get '/login' => 'dashboards#login'
    get '/settings' => 'dashboards#settings'
    get '/visitors' => 'dashboards#visitors'
  end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/front_page.rb
class FrontPage < ActiveRecord::Base
end

app/controllers/front_pages_controller.rb
class FrontPagesController < ApplicationController
  # before_action :authenticate, only: [:reveal_profile, :show_account_info]
  before_action :set_front_page, only: [:show, :edit, :update, :destroy]

  def main
    @user = User.new
  end
  # GET /front_pages
  # GET /front_pages.json
  def index
    @front_pages = FrontPage.all
  end

  # GET /front_pages/1
  # GET /front_pages/1.json
  def show
  end

  # GET /front_pages/new
  def new
    @front_page = FrontPage.new
  end

  # GET /front_pages/1/edit
  def edit
  end

  # POST /front_pages
  # POST /front_pages.json
  def create
    @front_page = FrontPage.new(front_page_params)

    respond_to do |format|
      if @front_page.save
        format.html { redirect_to @front_page, notice: 'Front page was successfully created.' }
        format.json { render :show, status: :created, location: @front_page }
      else
        format.html { render :new }
        format.json { render json: @front_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /front_pages/1
  # PATCH/PUT /front_pages/1.json
  def update
    respond_to do |format|
      if @front_page.update(front_page_params)
        format.html { redirect_to @front_page, notice: 'Front page was successfully updated.' }
        format.json { render :show, status: :ok, location: @front_page }
      else
        format.html { render :edit }
        format.json { render json: @front_page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /front_pages/1
  # DELETE /front_pages/1.json
  def destroy
    @front_page.destroy
    respond_to do |format|
      format.html { redirect_to front_pages_url, notice: 'Front page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # def authenticate
    #     is the user in the database
    # end

    # Use callbacks to share common setup or constraints between actions.
    def set_front_page
      @front_page = FrontPage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def front_page_params
      params[:front_page]
    end
end

app/helpers/front_pages_helper.rb
module FrontPagesHelper
end

app/views/front_pages/_form.html.erb
<%= form_for(@front_page) do |f| %>
  <% if @front_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@front_page.errors.count, "error") %> prohibited this front_page from being saved:</h2>

      <ul>
      <% @front_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/front_pages/_sign_up_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Sign Up" %>
  </div>
<% end %>

app/views/front_pages/_sign_up_form_for_mobile.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :email, placeholder: "Email", class: "bigger_signup" %>
  <%= f.password_field :password, placeholder: "Password", class: "bigger_signup" %> <br>
  <%= f.submit "Sign Up", class: "bigger_signup_button" %>

  <div class="field">
    <%# f.label :email %>
    <%# f.text_field :email, placeholder: "Email" %>
  </div>

  <div class="field">
    <%# f.label :password %>
    <%# f.password_field :password, placeholder: "Password" %>
  </div>
  <div class="actions">
    <%# f.submit "Sign Up" %>
  </div>
<% end %>

app/views/front_pages/edit.html.erb
<h1>Editing Front Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @front_page %> |
<%= link_to 'Back', front_pages_path %>

app/views/front_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Front Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @front_pages.each do |front_page| %>
      <tr>
        <td><%= link_to 'Show', front_page %></td>
        <td><%= link_to 'Edit', edit_front_page_path(front_page) %></td>
        <td><%= link_to 'Destroy', front_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Front page', new_front_page_path %>

app/views/front_pages/main.html.erb
<%= title "Bird Eye View of Your Website" %>

<div class="border">

  <div class="top_panel">
    <div class="left_side">
      <h1>Bird Eye View</h1>
    </div>

    <div class="right_side">

      <%= link_to "Pricing", "/pricing", class: "value link" %>
      <%= link_to "View pricing and plans", "/pricing", class: "value2 link" %>

      <%= link_to "Stories", "", class: "value link" %>
      <%= link_to "Success Stories", "/", class: "value2 link" %>

      <%= link_to "Help", "/support", class: "value link" %>
      <%= link_to "Support", "/support", class: "value2 link" %>

      <button type="button" name="button" class="value">Log in</button>
      <button type="button" name="button" class="value2">Sign in to your existing account</button>
    </div>
  </div>

  <p>
    View Data, Insights and Overview of your web site, web app and web businesses.
  </p>

  <div class="value">
    <%= render "sign_up_form_for_mobile" %>
  </div>

  <div class="value2">
    <%= render "sign_up_form" %>
  </div>

  <%= link_to "Try Free Trial for 30 Days - It's on us.", "/signup30daysfree", class: "link" %>

</div>

app/views/front_pages/new.html.erb
<h1>New Front Page</h1>

<%= render 'form' %>

<%= link_to 'Back', front_pages_path %>

app/views/front_pages/pricing.html.erb
<div class="border">

  <%= link_to "Back to home page", "/" %>

  <h1>Pricing</h1>

  <p>
    Show the pricing and free 30 days trials.
  </p>

</div>

app/views/front_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_front_page_path(@front_page) %> |
<%= link_to 'Back', front_pages_path %>

app/views/front_pages/support.html.erb
<div class="border">
  <%= link_to "Back to home page", "/" %>

  <h1>Support</h1>

</div>